rm -r -f ~/Dropbox/Projetos/dcl/docs/update/* 

cp ~/Dropbox/Projetos/dcl/dclsuite_site/index.html ~/Dropbox/Projetos/dcl/docs/update/
cp ~/Dropbox/Projetos/dcl/dclsuite_site/site.xml ~/Dropbox/Projetos/dcl/docs/update/
cp ~/Dropbox/Projetos/dcl/dclsuite_site/*.jar ~/Dropbox/Projetos/dcl/docs/update/
cp -r ~/Dropbox/Projetos/dcl/dclsuite_site/features ~/Dropbox/Projetos/dcl/docs/update/
cp -r ~/Dropbox/Projetos/dcl/dclsuite_site/plugins ~/Dropbox/Projetos/dcl/docs/update/

--rsync -ravzup --delete --exclude '.DS_Store' --exclude 'sync.script' -e ssh ~/Dropbox/Projetos/dcl/website/ terra@aserg.labsoft.dcc.ufmg.br:/var/www/dclsuite